# Generated by Django 5.0.6 on 2024-06-13 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(default='', max_length=40)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Доктор'), (2, 'Менеджер кадров'), ('Руководитель', 3)], default=1)),
                ('primary_skill', models.CharField(default='', max_length=10)),
                ('secondary_skills', models.CharField(default='', max_length=30)),
                ('bid', models.DecimalField(decimal_places=2, default='1.00', max_digits=3)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_month', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('time_break', models.TimeField()),
                ('time_total', models.DecimalField(decimal_places=3, max_digits=5)),
                ('research_type', models.CharField(max_length=13)),
                ('sys_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shedule', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
