# Generated by Django 5.0.6 on 2024-06-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Доктор'), ('Менеджер кадров', 2), ('Руководитель', 3)], default=1),
        ),
    ]
