# Generated by Django 5.0.6 on 2024-06-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='month_shed',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[('Доктор', 1), (2, 'Менеджер кадров'), ('Руководитель', 3)], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shed',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
