# Generated by Django 5.0.6 on 2024-06-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=40)),
                ('primary_skill', models.CharField(max_length=10)),
                ('secondary_skills', models.CharField(max_length=30)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=3)),
                ('day_of_month', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('time_break', models.TimeField()),
                ('time_total', models.DecimalField(decimal_places=3, max_digits=5)),
                ('research_type', models.CharField(max_length=5)),
            ],
        ),
    ]
