# Generated by Django 5.0.6 on 2024-06-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week_num', models.IntegerField()),
                ('dens', models.IntegerField()),
                ('kt', models.IntegerField()),
                ('kt1', models.IntegerField()),
                ('kt2', models.IntegerField()),
                ('mmg', models.IntegerField()),
                ('mrt', models.IntegerField()),
                ('mrt1', models.IntegerField()),
                ('mrt2', models.IntegerField()),
                ('rg', models.IntegerField()),
                ('flu', models.IntegerField()),
            ],
        ),
    ]
