# Generated by Django 5.0.6 on 2024-06-10 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='Иванов', max_length=30)),
                ('first_name', models.CharField(default='Иван', max_length=30)),
                ('patronymic', models.CharField(default='Иванович', max_length=40)),
                ('primary_skill', models.CharField(default='РГ', max_length=10)),
                ('secondary_skills', models.CharField(default='КТ', max_length=30)),
                ('bid', models.DecimalField(decimal_places=2, default='1.00', max_digits=3)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AlterModelOptions(
            name='shedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='primary_skill',
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='secondary_skills',
        ),
        migrations.AlterField(
            model_name='shedule',
            name='research_type',
            field=models.CharField(max_length=13),
        ),
        migrations.AddField(
            model_name='shedule',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shedule', to='accounts.employee'),
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='dr', max_length=2)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='identificator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='accounts.systemuser'),
        ),
    ]
