# Generated by Django 5.0.6 on 2024-06-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_employee_patronymic_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shedule',
            new_name='Schedule',
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[('Доктор', 1), (2, 'Менеджер кадров'), (3, 'Руководитель')], default=1),
        ),
    ]
