# Generated by Django 5.0.6 on 2024-06-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_shedule_schedule_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('type_not', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[('Доктор', 1), (2, 'Менеджер кадров'), ('Руководитель', 3)], default=1),
        ),
    ]
