# Generated by Django 5.0.6 on 2024-06-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='name_emp',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='notification',
            name='text_not',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Доктор'), (2, 'Менеджер кадров'), ('Руководитель', 3)], default=1),
        ),
    ]
