# Generated by Django 5.0.6 on 2024-06-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification_name_emp_notification_text_not_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Доктор'), ('Менеджер кадров', 2), (3, 'Руководитель')], default=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='name_emp',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text_not',
            field=models.TextField(default=''),
        ),
    ]
